# Generated by Django 5.0.6 on 2024-06-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='payment',
            new_name='paymentMethod',
        ),
    ]
