# Generated by Django 5.0.6 on 2024-06-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_payment_bill_paymentmethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='firtname',
            new_name='firstname',
        ),
    ]
